@startuml
class StaticFileHandler <<sealed>> {
    - <<readonly>> _path : string
    + StaticFileHandler(path:string)
    + Handle(neteworkStream:Stream) : void
}
IHandler <|-- StaticFileHandler
@enduml
