@startuml
class StaticFileHandler <<sealed>> {
    - <<readonly>> _path : string
    + StaticFileHandler(path:string)
    + Handle(networkStream:Stream, request:Request) : void
}
IHandler <|-- StaticFileHandler
@enduml
